create table public."DM" (
  user_id bigint not null,
  chat_id bigint null,
  "DM1" text null,
  "DM2" text null,
  "DM3" text null,
  "DM4" text null,
  "DM5" text null,
  constraint DM_pkey primary key (user_id)
) TABLESPACE pg_default;

create table public."Chat_history" (
  chat_id bigint generated by default as identity not null,
  message character varying null default ''::character varying,
  constraint Chat_history_pkey primary key (chat_id)
) TABLESPACE pg_default;