import psycopg2

import psycopg2
from dotenv import load_dotenv
import os

load_dotenv()


USER = os.getenv("user")
PASSWORD = os.getenv("password")
HOST = os.getenv("host")
PORT = os.getenv("port")
DBNAME = os.getenv("dbname")

def create_connection():
    """Create and return a database connection"""
    try:
        connection = psycopg2.connect(
            user=USER,
            password=PASSWORD,
            host=HOST,
            port=PORT,
            dbname=DBNAME
        )
        return connection
    except Exception as e:
        print(f"Failed to connect: {e}")
        return None


def create_tables():
    """Create DM and Chat_history tables"""
    conn = None
    try:
        conn = create_connection()
        if not conn:
            return
        
        cur = conn.cursor()
    
        cur.execute("""
            CREATE TABLE IF NOT EXISTS public."Chat_history" (
                chat_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                message CHARACTER VARYING NULL DEFAULT ''::CHARACTER VARYING,
                CONSTRAINT Chat_history_pkey PRIMARY KEY (chat_id)
            ) TABLESPACE pg_default;
        """)
        print("Created Chat_history table")
        
        cur.execute("""
            CREATE TABLE IF NOT EXISTS public."DM" (
                user_id BIGINT NOT NULL,
                chat_id BIGINT NULL,
                "DM1" TEXT NULL,
                "DM2" TEXT NULL,
                "DM3" TEXT NULL,
                "DM4" TEXT NULL,
                "DM5" TEXT NULL,
                CONSTRAINT DM_pkey PRIMARY KEY (user_id)
            ) TABLESPACE pg_default;
        """)
        print("Created DM table")
        
        conn.commit()
        print("Tables created successfully!")
        
    except Exception as e:
        print(f"Error creating tables: {e}")
        if conn:
            conn.rollback()
    finally:
        if conn:
            cur.close()
            conn.close()